# Generated by Django 5.1.15 on 2026-01-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobhistory',
            new_name='job_history_user_id_3970d1_idx',
            old_name='job_history_user_id_e74a4c_idx',
        ),
    ]
