# Generated by Django 6.0.2 on 2026-02-17 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                related_name="custom_roles",
                through="accounts.UserRole",
                through_fields=("role", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                choices=[("CO", "Colombia"), ("PA", "Panamá"), ("PE", "Perú")],
                default="CO",
                help_text="País donde trabaja el usuario",
                max_length=2,
                verbose_name="País",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_profile",
            field=models.CharField(
                choices=[
                    ("LINIERO", "Liniero"),
                    ("TECNICO", "Técnico"),
                    ("OPERADOR", "Operador"),
                    ("JEFE_CUADRILLA", "Jefe de Cuadrilla"),
                    ("INGENIERO_RESIDENTE", "Ingeniero Residente"),
                    ("COORDINADOR_HSEQ", "Coordinador HSEQ"),
                    ("COORDINADOR_VIZ", "Coordinador (Solo Visualización)"),
                    ("ADMINISTRADOR", "Administrador"),
                ],
                default="LINIERO",
                max_length=50,
                verbose_name="Perfil ocupacional",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Activo"), ("inactive", "Inactivo")],
                default="active",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
