# Generated by Django 5.2.11 on 2026-02-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_role_users_alter_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Código OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos de verificación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código OTP SMS',
                'verbose_name_plural': 'Códigos OTP SMS',
                'db_table': 'sms_otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='sms_otp_cod_user_id_8a8546_idx'), models.Index(fields=['code', 'user', 'is_used'], name='sms_otp_cod_code_5da8bc_idx')],
            },
        ),
    ]
