# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("hr", "Recursos Humanos"),
                            ("erp", "ERP"),
                            ("operations", "Operaciones"),
                            ("sso", "Single Sign-On"),
                            ("scorm", "SCORM"),
                            ("api", "API Externa"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("base_url", models.URLField(blank=True, verbose_name="URL base")),
                (
                    "api_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Versión de API"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        blank=True,
                        help_text="basic, bearer, oauth2, api_key, etc.",
                        max_length=50,
                        verbose_name="Tipo de autenticación",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Credenciales encriptadas",
                        verbose_name="Credenciales",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Headers adicionales"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuración"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("error", "Error"),
                            ("maintenance", "Mantenimiento"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última sincronización"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Último error"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sistema externo",
                "verbose_name_plural": "Sistemas externos",
                "db_table": "external_systems",
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(max_length=100, verbose_name="Operación"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Entrante"), ("outbound", "Saliente")],
                        max_length=20,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Exitoso"),
                            ("error", "Error"),
                            ("partial", "Parcial"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos de solicitud"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos de respuesta"
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Código HTTP"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (ms)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros procesados"
                    ),
                ),
                (
                    "records_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros fallidos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.externalsystem",
                        verbose_name="Sistema externo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de integración",
                "verbose_name_plural": "Logs de integración",
                "db_table": "integration_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="Lista de eventos que activan el webhook",
                        verbose_name="Eventos",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        help_text="Para firmar las solicitudes",
                        max_length=255,
                        verbose_name="Clave secreta",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Headers adicionales"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Reintentos"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Timeout (segundos)"
                    ),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última ejecución"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "webhooks",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=100, verbose_name="Evento")),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("retrying", "Reintentando"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Código HTTP"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Respuesta"),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próximo reintento"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (ms)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhook",
                        verbose_name="Webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de webhook",
                "verbose_name_plural": "Entregas de webhook",
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Ej: user, course, enrollment",
                        max_length=100,
                        verbose_name="Tipo de entidad",
                    ),
                ),
                (
                    "external_field",
                    models.CharField(max_length=200, verbose_name="Campo externo"),
                ),
                (
                    "internal_field",
                    models.CharField(max_length=200, verbose_name="Campo interno"),
                ),
                (
                    "transformation",
                    models.CharField(
                        blank=True,
                        help_text="Función de transformación a aplicar",
                        max_length=100,
                        verbose_name="Transformación",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Requerido"),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Valor por defecto"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "external_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="integrations.externalsystem",
                        verbose_name="Sistema externo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeo de datos",
                "verbose_name_plural": "Mapeos de datos",
                "db_table": "data_mappings",
                "unique_together": {
                    ("external_system", "entity_type", "external_field")
                },
            },
        ),
    ]
