# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("objectives", models.TextField(blank=True, verbose_name="Objetivos")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Duración estimada en minutos",
                        verbose_name="Duración (minutos)",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Obligatorio"),
                            ("optional", "Opcional"),
                            ("refresher", "Refuerzo"),
                        ],
                        default="mandatory",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Nivel de riesgo",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/thumbnails/",
                        verbose_name="Imagen miniatura",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versión"),
                ),
                (
                    "target_profiles",
                    models.JSONField(
                        default=list,
                        help_text="Lista de perfiles ocupacionales para este curso",
                        verbose_name="Perfiles objetivo",
                    ),
                ),
                (
                    "validity_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Meses de validez de la certificación (null = sin vencimiento)",
                        null=True,
                        verbose_name="Validez (meses)",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de publicación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_for",
                        to="courses.course",
                        verbose_name="Prerrequisitos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "db_table": "courses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Inscrito"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("expired", "Vencido"),
                            ("dropped", "Abandonado"),
                        ],
                        default="enrolled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "db_table": "enrollments",
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nombre de archivo"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nombre original"),
                ),
                (
                    "file",
                    models.FileField(upload_to="media_assets/", verbose_name="Archivo"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("image", "Imagen"),
                            ("document", "Documento"),
                            ("scorm", "Paquete SCORM"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME type"),
                ),
                ("size", models.PositiveBigIntegerField(verbose_name="Tamaño (bytes)")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media_assets/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "compressed_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media_assets/offline/",
                        verbose_name="Archivo comprimido (offline)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("ready", "Listo"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Error de procesamiento"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (segundos)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso multimedia",
                "verbose_name_plural": "Recursos multimedia",
                "db_table": "media_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "db_table": "modules",
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("scorm", "SCORM"),
                            ("interactive", "Interactivo"),
                            ("audio", "Audio"),
                            ("quiz", "Quiz"),
                            ("text", "Texto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido HTML o texto",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "content_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="courses/content/",
                        verbose_name="Archivo de contenido",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="URL del video"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duración (minutos)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Obligatorio"),
                ),
                (
                    "is_offline_available",
                    models.BooleanField(
                        default=True, verbose_name="Disponible offline"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.module",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección",
                "verbose_name_plural": "Lecciones",
                "db_table": "lessons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo empleado (segundos)"
                    ),
                ),
                (
                    "last_position",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Posición del video/contenido para continuar",
                        verbose_name="Última posición",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="courses.enrollment",
                        verbose_name="Inscripción",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de lección",
                "verbose_name_plural": "Progreso de lecciones",
                "db_table": "lesson_progress",
                "unique_together": {("enrollment", "lesson")},
            },
        ),
    ]
