# Generated by Django 5.1.15 on 2026-01-05 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_contracts_category_course_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagen"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Documento"),
                            ("template", "Plantilla"),
                            ("infographic", "Infografía"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="resource_library/", verbose_name="Archivo"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resource_library/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Tamaño (bytes)"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiquetas"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="Veces usado"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Público"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="courses.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso de biblioteca",
                "verbose_name_plural": "Recursos de biblioteca",
                "db_table": "resource_library",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScormPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_file",
                    models.FileField(
                        upload_to="scorm_packages/", verbose_name="Paquete SCORM"
                    ),
                ),
                (
                    "extracted_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta extraída"
                    ),
                ),
                (
                    "entry_point",
                    models.CharField(
                        blank=True,
                        help_text="HTML de inicio del paquete",
                        max_length=255,
                        verbose_name="Punto de entrada",
                    ),
                ),
                (
                    "scorm_version",
                    models.CharField(
                        choices=[
                            ("1.2", "SCORM 1.2"),
                            ("2004", "SCORM 2004"),
                            ("xapi", "xAPI/TinCan"),
                        ],
                        default="1.2",
                        max_length=10,
                        verbose_name="Versión SCORM",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Subido"),
                            ("extracting", "Extrayendo"),
                            ("validating", "Validando"),
                            ("ready", "Listo"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "manifest_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos del manifiesto"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Tamaño (bytes)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_package",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete SCORM",
                "verbose_name_plural": "Paquetes SCORM",
                "db_table": "scorm_packages",
            },
        ),
        migrations.CreateModel(
            name="ScormAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de intento"
                    ),
                ),
                (
                    "lesson_status",
                    models.CharField(
                        choices=[
                            ("not attempted", "No iniciado"),
                            ("incomplete", "Incompleto"),
                            ("completed", "Completado"),
                            ("passed", "Aprobado"),
                            ("failed", "Reprobado"),
                        ],
                        default="not attempted",
                        max_length=20,
                        verbose_name="Estado de lección",
                    ),
                ),
                (
                    "score_raw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Puntuación",
                    ),
                ),
                (
                    "score_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Puntuación mínima",
                    ),
                ),
                (
                    "score_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Puntuación máxima",
                    ),
                ),
                (
                    "session_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tiempo de sesión"
                    ),
                ),
                (
                    "total_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tiempo total"
                    ),
                ),
                (
                    "suspend_data",
                    models.TextField(
                        blank=True,
                        help_text="Datos para continuar la sesión",
                        verbose_name="Datos de suspensión",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Última ubicación en el contenido",
                        max_length=255,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "interactions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Interacciones"
                    ),
                ),
                (
                    "cmi_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Todos los datos CMI del intento",
                        verbose_name="Datos CMI",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inicio"),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Último acceso"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_attempts",
                        to="courses.enrollment",
                        verbose_name="Inscripción",
                    ),
                ),
                (
                    "scorm_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="courses.scormpackage",
                        verbose_name="Paquete SCORM",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento SCORM",
                "verbose_name_plural": "Intentos SCORM",
                "db_table": "scorm_attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Número de versión"),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Complete course data snapshot",
                        verbose_name="Snapshot",
                    ),
                ),
                ("changelog", models.TextField(blank=True, verbose_name="Cambios")),
                (
                    "is_major_version",
                    models.BooleanField(default=False, verbose_name="Versión mayor"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de publicación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de curso",
                "verbose_name_plural": "Versiones de curso",
                "db_table": "course_versions",
                "ordering": ["-version_number"],
                "unique_together": {("course", "version_number")},
            },
        ),
    ]
