# Generated by Django 5.1.15 on 2026-01-26 23:04

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_risk_level_and_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal', max_length=7, validators=[apps.core.validators.HexColorValidator()], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_profiles',
            field=models.JSONField(default=list, help_text='Lista de perfiles ocupacionales para este curso', validators=[apps.core.validators.JSONSchemaValidator({'items': {'type': 'string'}, 'type': 'list'}, message='target_profiles debe ser una lista de strings.')], verbose_name='Perfiles objetivo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[apps.core.validators.validate_percentage], verbose_name='Progreso (%)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/content/', validators=[apps.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'webm', 'mov', 'avi', 'mkv', 'mp3', 'wav', 'ogg', 'm4a', 'aac', 'zip'], message='Tipo de archivo no permitido.')], verbose_name='Archivo de contenido'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, validators=[apps.core.validators.SafeURLValidator(allow_http=True, message='Ingrese una URL válida.')], verbose_name='URL del video'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[apps.core.validators.validate_percentage], verbose_name='Progreso (%)'),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='package_file',
            field=models.FileField(upload_to='scorm_packages/', validators=[apps.core.validators.FileExtensionValidator(['zip'], message='Los paquetes SCORM deben ser archivos ZIP.')], verbose_name='Paquete SCORM'),
        ),
    ]
