# Generated by Django 4.2.21 on 2026-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_category_color_alter_course_target_profiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador unico (ej: LINIERO, TECNICO)', max_length=50, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Perfil Ocupacional',
                'verbose_name_plural': 'Tipos de Perfiles Ocupacionales',
                'db_table': 'job_profile_types',
                'ordering': ['order', 'name'],
            },
        ),
    ]
