# Generated by Django 6.0.2 on 2026-02-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_course_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_presential",
            field=models.BooleanField(
                default=False,
                help_text="Si la lección requiere asistencia presencial",
                verbose_name="Presencial",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("pdf", "PDF"),
                    ("scorm", "SCORM"),
                    ("interactive", "Interactivo"),
                    ("audio", "Audio"),
                    ("quiz", "Quiz"),
                    ("text", "Texto"),
                    ("presential", "Presencial"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="LessonEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("photo", "Fotografía"),
                            ("attendance", "Lista de Asistencia"),
                            ("certificate", "Certificado"),
                            ("other", "Otro"),
                        ],
                        default="photo",
                        max_length=20,
                        verbose_name="Tipo de evidencia",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="lesson_evidences/%Y/%m/", verbose_name="Archivo"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Si la evidencia ha sido verificada por un supervisor",
                        verbose_name="Verificado",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de verificación"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_evidences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidences_verified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de lección",
                "verbose_name_plural": "Evidencias de lección",
                "db_table": "lesson_evidences",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(fields=["lesson", "user"], name="lesson_evid_lesson__fe5995_idx")
                ],
            },
        ),
    ]
