# Generated by Django 5.1.15 on 2026-03-05 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_is_presential_alter_lesson_lesson_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(verbose_name='Fecha de completado')),
                ('progress', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Progreso alcanzado (%)')),
                ('reset_reason', models.CharField(default='Reactivación de usuario', max_length=100, verbose_name='Motivo del reinicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to='courses.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de completación',
                'verbose_name_plural': 'Registros de completación',
                'db_table': 'completion_records',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'course'], name='completion__user_id_766351_idx')],
            },
        ),
    ]
