# Generated by Django 5.1.15 on 2026-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_add_completion_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen grande que se muestra en el encabezado del curso', null=True, upload_to='courses/banners/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='course',
            name='theme_color',
            field=models.CharField(blank=True, default='', help_text='Color hexadecimal del tema del curso (ej: #3B82F6)', max_length=7, verbose_name='Color del tema'),
        ),
        migrations.AddField(
            model_name='module',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen que se muestra al inicio del módulo', null=True, upload_to='courses/modules/', verbose_name='Imagen de portada'),
        ),
    ]
