# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("exam", "Examen"),
                            ("practice", "Práctica"),
                            ("survey", "Encuesta"),
                        ],
                        default="quiz",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Porcentaje mínimo para aprobar",
                        verbose_name="Puntaje mínimo (%)",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tiempo límite (minutos)"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="0 = intentos ilimitados",
                        verbose_name="Intentos máximos",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(default=True, verbose_name="Mezclar preguntas"),
                ),
                (
                    "shuffle_answers",
                    models.BooleanField(
                        default=True, verbose_name="Mezclar respuestas"
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True,
                        help_text="Mostrar respuestas correctas al finalizar",
                        verbose_name="Mostrar respuestas correctas",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "db_table": "assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En progreso"),
                            ("submitted", "Enviado"),
                            ("graded", "Calificado"),
                            ("expired", "Expirado"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de intento"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntaje (%)",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos obtenidos"
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(blank=True, null=True, verbose_name="Aprobado"),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo empleado (segundos)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de calificación"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.assessment",
                        verbose_name="Evaluación",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts_graded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Calificado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de evaluación",
                "verbose_name_plural": "Intentos de evaluación",
                "db_table": "assessment_attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Selección única"),
                            ("multiple_choice", "Selección múltiple"),
                            ("true_false", "Verdadero/Falso"),
                            ("short_answer", "Respuesta corta"),
                            ("essay", "Ensayo"),
                            ("matching", "Emparejamiento"),
                            ("ordering", "Ordenamiento"),
                        ],
                        default="single_choice",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("text", models.TextField(verbose_name="Pregunta")),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explicación de la respuesta correcta",
                        verbose_name="Explicación",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="Puntos"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assessments/questions/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.assessment",
                        verbose_name="Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Respuesta")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Es correcta"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Retroalimentación específica para esta respuesta",
                        verbose_name="Retroalimentación",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.question",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "db_table": "answers",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="Para preguntas de respuesta corta o ensayo",
                        verbose_name="Respuesta de texto",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Es correcta"
                    ),
                ),
                (
                    "points_awarded",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntos otorgados",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Retroalimentación"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_answers",
                        to="assessments.assessmentattempt",
                        verbose_name="Intento",
                    ),
                ),
                (
                    "selected_answers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="selections",
                        to="assessments.answer",
                        verbose_name="Respuestas seleccionadas",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_answers",
                        to="assessments.question",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de intento",
                "verbose_name_plural": "Respuestas de intento",
                "db_table": "attempt_answers",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
