# Generated by Django 5.2.10 on 2026-01-10 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'assessment'], name='assessment__user_id_da3461_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['status', 'user'], name='assessment__status_9f4d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment', 'order'], name='questions_assessm_105ca2_idx'),
        ),
    ]
