# Generated by Django 5.1.15 on 2026-01-26 23:04

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_add_missing_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.PositiveIntegerField(default=80, help_text='Porcentaje mínimo para aprobar', validators=[apps.core.validators.validate_percentage], verbose_name='Puntaje mínimo (%)'),
        ),
    ]
