# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "target_profiles",
                    models.JSONField(
                        default=list,
                        help_text="Lista de perfiles ocupacionales para esta ruta",
                        verbose_name="Perfiles objetivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("active", "Activo"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Si es obligatorio para los perfiles objetivo",
                        verbose_name="Obligatorio",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="Tiempo estimado para completar la ruta",
                        verbose_name="Duración estimada (días)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="learning_paths/",
                        verbose_name="Imagen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_paths_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta de aprendizaje",
                "verbose_name_plural": "Rutas de aprendizaje",
                "db_table": "learning_paths",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PathAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Asignado"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("overdue", "Vencido"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="path_assignments_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="learning_paths.learningpath",
                        verbose_name="Ruta",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de ruta",
                "verbose_name_plural": "Asignaciones de ruta",
                "db_table": "path_assignments",
                "unique_together": {("user", "learning_path")},
            },
        ),
        migrations.CreateModel(
            name="PathCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Requerido"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_inclusions",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_courses",
                        to="learning_paths.learningpath",
                        verbose_name="Ruta",
                    ),
                ),
                (
                    "unlock_after",
                    models.ForeignKey(
                        blank=True,
                        help_text="Curso que debe completarse antes de desbloquear este",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocks",
                        to="learning_paths.pathcourse",
                        verbose_name="Desbloquear después de",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso en ruta",
                "verbose_name_plural": "Cursos en ruta",
                "db_table": "path_courses",
                "ordering": ["order"],
                "unique_together": {("learning_path", "course")},
            },
        ),
    ]
