# Generated by Django 6.0.2 on 2026-02-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_paths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="country",
            field=models.CharField(
                choices=[("CO", "Colombia"), ("PA", "Panamá"), ("PE", "Perú")],
                default="CO",
                help_text="País donde aplica esta ruta",
                max_length=2,
                verbose_name="País",
            ),
        ),
    ]
