# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icono"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="lessons_learned.category",
                        verbose_name="Categoría padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "lesson_learned_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LessonLearned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("incident", "Incidente"),
                            ("near_miss", "Casi accidente"),
                            ("good_practice", "Buena práctica"),
                            ("improvement", "Mejora"),
                            ("observation", "Observación"),
                        ],
                        default="observation",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending_review", "Pendiente de revisión"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "situation",
                    models.TextField(
                        help_text="Descripción de la situación o contexto",
                        verbose_name="Situación",
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True,
                        help_text="Análisis de la causa raíz",
                        verbose_name="Causa raíz",
                    ),
                ),
                (
                    "lesson",
                    models.TextField(
                        help_text="La lección aprendida", verbose_name="Lección"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        help_text="Acciones recomendadas",
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Proyecto, línea o sitio donde ocurrió",
                        max_length=200,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "date_occurred",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del evento"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiquetas"
                    ),
                ),
                (
                    "target_profiles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Perfiles objetivo"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de revisión"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Notas de revisión"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vistas"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons_learned",
                        to="lessons_learned.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons_learned_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons_learned_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección aprendida",
                "verbose_name_plural": "Lecciones aprendidas",
                "db_table": "lessons_learned",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Aprobado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="lessons_learned.lessoncomment",
                        verbose_name="Respuesta a",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "lesson_learned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="lessons_learned.lessonlearned",
                        verbose_name="Lección aprendida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "db_table": "lesson_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="lessons_learned/attachments/", verbose_name="Archivo"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagen"),
                            ("video", "Video"),
                            ("document", "Documento"),
                            ("other", "Otro"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nombre original"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descripción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson_learned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="lessons_learned.lessonlearned",
                        verbose_name="Lección aprendida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "db_table": "lesson_attachments",
            },
        ),
    ]
