# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreopTalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "key_points",
                    models.JSONField(default=list, verbose_name="Puntos clave"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="Ubicación"),
                ),
                (
                    "work_activity",
                    models.CharField(
                        max_length=200, verbose_name="Actividad de trabajo"
                    ),
                ),
                (
                    "weather_conditions",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Condiciones climáticas",
                    ),
                ),
                (
                    "special_risks",
                    models.TextField(blank=True, verbose_name="Riesgos especiales"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Fecha programada")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (minutos)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud GPS",
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitud GPS",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talks_conducted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizada por",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talks_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charla pre-operacional",
                "verbose_name_plural": "Charlas pre-operacionales",
                "db_table": "preop_talks",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="TalkAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="talks/attachments/", verbose_name="Archivo"
                    ),
                ),
                ("file_type", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nombre original"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descripción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="preop_talks.preoptalk",
                        verbose_name="Charla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "db_table": "talk_attachments",
            },
        ),
        migrations.CreateModel(
            name="TalkTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "talk_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("special", "Especial"),
                            ("emergency", "Emergencia"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "key_points",
                    models.JSONField(default=list, verbose_name="Puntos clave"),
                ),
                (
                    "safety_topics",
                    models.JSONField(default=list, verbose_name="Temas de seguridad"),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Duración estimada (minutos)"
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(default=True, verbose_name="Requiere firma"),
                ),
                (
                    "target_activities",
                    models.JSONField(
                        default=list,
                        help_text="Tipos de actividades para las que aplica",
                        verbose_name="Actividades objetivo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talk_templates_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de charla",
                "verbose_name_plural": "Plantillas de charla",
                "db_table": "talk_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="preoptalk",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="preop_talks.talktemplate",
                verbose_name="Plantilla",
            ),
        ),
        migrations.CreateModel(
            name="TalkAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="talks/signatures/",
                        verbose_name="Firma",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de firma"
                    ),
                ),
                (
                    "understood_content",
                    models.BooleanField(
                        default=True, verbose_name="Entendió el contenido"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comentarios")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="preop_talks.preoptalk",
                        verbose_name="Charla",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistente",
                "verbose_name_plural": "Asistentes",
                "db_table": "talk_attendees",
                "unique_together": {("talk", "user")},
            },
        ),
    ]
