# Generated by Django 6.0.2 on 2026-02-17 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preop_talks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="talktemplate",
            name="recurrence_months",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Cada cuántos meses se recicla esta plantilla",
                verbose_name="Recurrencia (meses)",
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "unique_link",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="Enlace único"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("active", "Activo"),
                            ("expired", "Expirado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="alerts/attachments/%Y/%m/",
                        verbose_name="Archivo adjunto",
                    ),
                ),
                (
                    "requires_verification",
                    models.BooleanField(
                        default=True,
                        help_text="Si el usuario debe responder preguntas para confirmar lectura",
                        verbose_name="Requiere verificación",
                    ),
                ),
                (
                    "target_profiles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Perfiles ocupacionales que deben ver esta alerta",
                        verbose_name="Perfiles objetivo",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de publicación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha de expiración"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta/Divulgación",
                "verbose_name_plural": "Alertas/Divulgaciones",
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertVerificationQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_text", models.CharField(max_length=500, verbose_name="Pregunta")),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Respuesta esperada para verificar comprensión",
                        max_length=200,
                        verbose_name="Respuesta correcta",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_questions",
                        to="preop_talks.alert",
                        verbose_name="Alerta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de verificación",
                "verbose_name_plural": "Preguntas de verificación",
                "db_table": "alert_verification_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AlertAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de acceso"),
                ),
                ("verified", models.BooleanField(default=False, verbose_name="Verificado")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de verificación"
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Respuestas a las preguntas de verificación",
                        verbose_name="Respuestas",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="preop_talks.alert",
                        verbose_name="Alerta",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceso a alerta",
                "verbose_name_plural": "Accesos a alertas",
                "db_table": "alert_accesses",
                "unique_together": {("alert", "user")},
            },
        ),
    ]
