# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflinePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versión"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Construyendo"),
                            ("ready", "Listo"),
                            ("outdated", "Desactualizado"),
                            ("error", "Error"),
                        ],
                        default="building",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "package_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="offline_packages/",
                        verbose_name="Archivo del paquete",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Tamaño del archivo"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Checksum"
                    ),
                ),
                (
                    "includes_videos",
                    models.BooleanField(default=True, verbose_name="Incluye videos"),
                ),
                (
                    "includes_documents",
                    models.BooleanField(
                        default=True, verbose_name="Incluye documentos"
                    ),
                ),
                (
                    "includes_assessments",
                    models.BooleanField(
                        default=True, verbose_name="Incluye evaluaciones"
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Lista de contenidos incluidos",
                        verbose_name="Manifiesto",
                    ),
                ),
                (
                    "build_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de construcción"
                    ),
                ),
                (
                    "build_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de construcción"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_packages",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete offline",
                "verbose_name_plural": "Paquetes offline",
                "db_table": "offline_packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=100, verbose_name="ID del dispositivo"),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de descarga"
                    ),
                ),
                (
                    "download_completed",
                    models.BooleanField(
                        default=False, verbose_name="Descarga completada"
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último acceso"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="sync.offlinepackage",
                        verbose_name="Paquete",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_downloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descarga de paquete",
                "verbose_name_plural": "Descargas de paquete",
                "db_table": "package_downloads",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=100, verbose_name="ID del dispositivo"),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nombre del dispositivo",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("upload", "Subida"),
                            ("download", "Descarga"),
                            ("bidirectional", "Bidireccional"),
                        ],
                        default="bidirectional",
                        max_length=20,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("partial", "Parcial"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "records_uploaded",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros subidos"
                    ),
                ),
                (
                    "records_downloaded",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros descargados"
                    ),
                ),
                (
                    "bytes_transferred",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Bytes transferidos"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Detalles del error"
                    ),
                ),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Timestamp del cliente"
                    ),
                ),
                (
                    "server_timestamp",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Timestamp del servidor"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de sincronización",
                "verbose_name_plural": "Logs de sincronización",
                "db_table": "sync_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Nombre del modelo"),
                ),
                (
                    "record_id",
                    models.CharField(max_length=100, verbose_name="ID del registro"),
                ),
                ("server_data", models.JSONField(verbose_name="Datos del servidor")),
                ("client_data", models.JSONField(verbose_name="Datos del cliente")),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("server_wins", "Servidor gana"),
                            ("client_wins", "Cliente gana"),
                            ("merged", "Fusionado"),
                            ("manual", "Manual"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Resolución",
                    ),
                ),
                (
                    "resolved_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos resueltos"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de resolución"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_conflicts_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resuelto por",
                    ),
                ),
                (
                    "sync_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="sync.synclog",
                        verbose_name="Log de sincronización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflicto de sincronización",
                "verbose_name_plural": "Conflictos de sincronización",
                "db_table": "sync_conflicts",
                "ordering": ["-created_at"],
            },
        ),
    ]
