# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Por defecto"),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict,
                        help_text="Configuración del layout del dashboard",
                        verbose_name="Layout",
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(
                        default=list,
                        help_text="Lista de widgets del dashboard",
                        verbose_name="Widgets",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Público"),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Roles permitidos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboards_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "db_table": "dashboards",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("training", "Capacitación"),
                            ("compliance", "Cumplimiento"),
                            ("assessment", "Evaluaciones"),
                            ("certification", "Certificaciones"),
                            ("progress", "Progreso"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "default_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="Formato por defecto",
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/templates/",
                        verbose_name="Archivo de plantilla",
                    ),
                ),
                (
                    "query_definition",
                    models.JSONField(
                        default=dict,
                        help_text="Definición de filtros y datos del reporte",
                        verbose_name="Definición de consulta",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="Definición de columnas del reporte",
                        verbose_name="Columnas",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=list,
                        help_text="Filtros que el usuario puede aplicar",
                        verbose_name="Filtros disponibles",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="Programable"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_templates_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de reporte",
                "verbose_name_plural": "Plantillas de reporte",
                "db_table": "report_templates",
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        max_length=20,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("generating", "Generando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(default=dict, verbose_name="Filtros aplicados"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/generated/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Tamaño del archivo"
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de filas"
                    ),
                ),
                (
                    "generation_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de generación"
                    ),
                ),
                (
                    "generation_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de generación"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de expiración"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado por",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="reports.reporttemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte generado",
                "verbose_name_plural": "Reportes generados",
                "db_table": "generated_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("biweekly", "Quincenal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        max_length=20,
                        verbose_name="Formato",
                    ),
                ),
                ("filters", models.JSONField(default=dict, verbose_name="Filtros")),
                (
                    "recipients",
                    models.JSONField(default=list, verbose_name="Destinatarios"),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0=Lunes, 6=Domingo",
                        null=True,
                        verbose_name="Día de la semana",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Día del mes"
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        help_text="Hora a la que se genera el reporte",
                        verbose_name="Hora del día",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última ejecución"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próxima ejecución"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reporttemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte programado",
                "verbose_name_plural": "Reportes programados",
                "db_table": "scheduled_reports",
            },
        ),
        migrations.CreateModel(
            name="UserDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_widgets",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Widgets personalizados"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_selections",
                        to="reports.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard de usuario",
                "verbose_name_plural": "Dashboards de usuario",
                "db_table": "user_dashboards",
            },
        ),
    ]
