# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "template_file",
                    models.FileField(
                        help_text="Archivo HTML/PDF de la plantilla",
                        upload_to="certificates/templates/",
                        verbose_name="Archivo de plantilla",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/backgrounds/",
                        verbose_name="Imagen de fondo",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/signatures/",
                        verbose_name="Imagen de firma",
                    ),
                ),
                (
                    "signer_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del firmante"
                    ),
                ),
                (
                    "signer_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Cargo del firmante"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de certificado",
                "verbose_name_plural": "Plantillas de certificado",
                "db_table": "certificate_templates",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de certificado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("issued", "Emitido"),
                            ("revoked", "Revocado"),
                            ("expired", "Vencido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntaje (%)",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/issued/",
                        verbose_name="Archivo de certificado",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de revocación"
                    ),
                ),
                (
                    "revoked_reason",
                    models.TextField(blank=True, verbose_name="Motivo de revocación"),
                ),
                (
                    "verification_url",
                    models.URLField(blank=True, verbose_name="URL de verificación"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/qr/",
                        verbose_name="Código QR",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="certifications.certificatetemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "db_table": "certificates",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de verificación"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("is_valid", models.BooleanField(default=True, verbose_name="Válido")),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="certifications.certificate",
                        verbose_name="Certificado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verificación de certificado",
                "verbose_name_plural": "Verificaciones de certificado",
                "db_table": "certificate_verifications",
                "ordering": ["-verified_at"],
            },
        ),
    ]
