# Generated by Django 5.1.15 on 2026-01-26 23:04

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[apps.core.validators.validate_percentage], verbose_name='Puntaje (%)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_url',
            field=models.URLField(blank=True, validators=[apps.core.validators.SafeURLValidator(message='La URL debe usar HTTPS.', schemes=['https'])], verbose_name='URL de verificación'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/', validators=[apps.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Solo se permiten imágenes: %(allowed)s')], verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/logos/', validators=[apps.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Solo se permiten imágenes: %(allowed)s')], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/signatures/', validators=[apps.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Solo se permiten imágenes: %(allowed)s')], verbose_name='Imagen de firma'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_file',
            field=models.FileField(help_text='Archivo HTML/PDF de la plantilla', upload_to='certificates/templates/', validators=[apps.core.validators.FileExtensionValidator(['html', 'htm', 'pdf'], message='Las plantillas de certificado deben ser HTML o PDF.')], verbose_name='Archivo de plantilla'),
        ),
    ]
