# Generated by Django 5.1.15 on 2026-01-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Asunto del email o título de la notificación",
                        max_length=200,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Contenido de la notificación. Usa {{variable}} para variables",
                        verbose_name="Cuerpo",
                    ),
                ),
                (
                    "html_body",
                    models.TextField(
                        blank=True,
                        help_text="Versión HTML del contenido para emails",
                        verbose_name="Cuerpo HTML",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push"),
                            ("sms", "SMS"),
                            ("in_app", "En la aplicación"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de notificación",
                "verbose_name_plural": "Plantillas de notificación",
                "db_table": "notification_templates",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push"),
                            ("sms", "SMS"),
                            ("in_app", "En la aplicación"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Asunto")),
                ("body", models.TextField(verbose_name="Cuerpo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL a la que dirigir al usuario",
                        verbose_name="URL de acción",
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texto de acción"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Intentos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(verbose_name="Endpoint")),
                (
                    "p256dh_key",
                    models.CharField(max_length=255, verbose_name="Clave P256DH"),
                ),
                (
                    "auth_key",
                    models.CharField(
                        max_length=255, verbose_name="Clave de autenticación"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nombre del dispositivo",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de dispositivo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now=True, verbose_name="Último uso"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción push",
                "verbose_name_plural": "Suscripciones push",
                "db_table": "push_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email habilitado"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="Push habilitado"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS habilitado"),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, verbose_name="En app habilitado"),
                ),
                (
                    "course_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Recordatorios de cursos"
                    ),
                ),
                (
                    "assessment_results",
                    models.BooleanField(
                        default=True, verbose_name="Resultados de evaluaciones"
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=True, verbose_name="Certificados emitidos"
                    ),
                ),
                (
                    "new_assignments",
                    models.BooleanField(
                        default=True, verbose_name="Nuevas asignaciones"
                    ),
                ),
                (
                    "deadline_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Recordatorios de fecha límite"
                    ),
                ),
                (
                    "lesson_learned_updates",
                    models.BooleanField(
                        default=True,
                        verbose_name="Actualizaciones de lecciones aprendidas",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Inicio de horas silenciosas",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Fin de horas silenciosas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de notificación",
                "verbose_name_plural": "Preferencias de notificación",
                "db_table": "user_notification_preferences",
            },
        ),
    ]
