# Generated by Django 5.1.15 on 2026-01-26 23:04

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_missing_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL a la que dirigir al usuario', validators=[apps.core.validators.SafeURLValidator(allow_http=True, message='Ingrese una URL válida.')], verbose_name='URL de acción'),
        ),
    ]
